#!/usr/bin/env bash

set -Eeo pipefail

###########################
# Local Config Parameters #
###########################

AWS_DEFAULT_REGION=eu-west-2
IMAGE_REPO_NAME=deductions/nems-event-processor
export NHS_SERVICE=nems-event-processor

function check_env {
  if [[ -z "${NHS_ENVIRONMENT}" ]]; then
    echo "Must set NHS_ENVIRONMENT"
    exit 1
  fi
}

function configure_local_envs {
  export LOCALSTACK_URL="http://localhost:4566"
  export AWS_REGION="eu-west-2"
  export AWS_DEFAULT_REGION="eu-west-2"
  export NHS_ENVIRONMENT="local"
}


##############
# Localstack #
##############

function start_localstack {
  echo "################################"
  echo "##### Starting Localstack ######"
  echo "################################"
  docker compose -f docker-compose.localstack-local.yaml up -d
}

function stop_localstack {
  echo "################################"
  echo "##### Stopping Localstack ######"
  echo "################################"
  docker compose -f docker-compose.localstack-local.yaml down
}

###########
## TASKS ##
###########

command="$1"
case "${command}" in
  build)
      rm -rf build/
      ./gradlew build -x integration
      ;;
  test_unit)
      ./gradlew test
      ;;
  test_integration)
      configure_local_envs
      start_localstack
      ./gradlew --info integration
      stop_localstack
      ;;
  code_quality)
      configure_local_envs
      start_localstack
      gradle check -x test -x integration
      stop_localstack
      ;;
  test_all)
      configure_local_envs
      start_localstack
      ./gradlew clean test integration jacocoTestCoverageVerification check
      stop_localstack
      ;;
  run_sonar)
      _assume_environment_role $NHS_ENVIRONMENT
      configure_local_envs
      configure_sonar_environment_variable
      start_localstack
      ./gradlew build sonar --info
      stop_localstack
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
